## Numpy array and basics

In [10]:
import numpy as np

### Creating Array From List

In [11]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6],[7,8, 9]])
print("2D Array ", arr_2d)

1D Array  [1 2 3 4 5]
2D Array  [[1 2 3]
 [4 5 6]
 [7 8 9]]


### List vs Numpy array

In [12]:
py_list = [1,2,3]
print("Pyhton list multiplication ", py_list*2)


np_array = np.array([1,2,3]) # element wise multiplication
print("Numpy array multiplication ", np_array*2)


import time

start= time.time()
py_list = [i*2 for i in range(1000000)]
print("\n Python list multiplication time: ", time.time()-start)


start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy array multiplication time: ", time.time()-start)




Pyhton list multiplication  [1, 2, 3, 1, 2, 3]
Numpy array multiplication  [2 4 6]

 Python list multiplication time:  0.08919429779052734

 Numpy array multiplication time:  0.00399017333984375


### Creating array from scratch

In [ ]:
zeros = np.zeros((3,4))
print("Zeros Array : \n",zeros)

ones = np.ones((3,4))
print("Ones Array : \n",ones)

full = np.full((3,4),7)
print("Full Array : \n",full)


random = np.random.random((2,3))
print("Random Array : \n",random)


sequence = np.arange(0,10,2)
print("Sequence Array : \n",sequence)


Zeros Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array : 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Random Array : 
 [[0.88920146 0.4364194  0.60086296]
 [0.00096272 0.89568453 0.92991096]]
Sequence Array : 
 [1 3 5 7 9]
