In [2]:
import numpy as np

## Array 

In [4]:

arr_2d = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print("Specefic Element of 2D array: ", arr_2d[1,2])

print("Entire Row : ", arr_2d[1])
print("Entire Column : ", arr_2d[:,1])

Specefic Element of 2D array:  6
Entire Row :  [4 5 6]
Entire Column :  [2 5 8]


### Sorting


In [ ]:
unsorted = np.array([3,1,4,1,5,9,2,3,1,6])
print("Sorted array : ", np.sort(unsorted))

arr_2d = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted array by column : \n", np.sort(arr_2d , axis=0))
print("Sorted array by row : \n", np.sort(arr_2d , axis=1))

Sorted array :  [1 1 1 2 3 3 4 5 6 9]
Sorted array by column : 
 [[1 1]
 [2 2]
 [3 3]]


### Filtering ANd Filter with Mask

In [14]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers%2 == 0]
print("Even numbers in the array: ", even_number)

mask = numbers > 5
print("Numbers greater than 5: ", numbers[mask])

Even numbers in the array:  [ 2  4  6  8 10]
Numbers greater than 5:  [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [ ]:
indices  = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where result: ", where_result) # returns the positions
print("Np where result for numbers: " , numbers[where_result])


[1 3 5]
NP where result:  (array([5, 6, 7, 8, 9]),)
Np where result for numbers:  [ 6  7  8  9 10]


In [21]:
condition_array = np.where(numbers >5 , "true" , "false")
print(condition_array)
condition_array = np.where(numbers >5 , numbers*2 , numbers)
print("condition array: " , condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']
condition array:  [ 1  2  3  4  5 12 14 16 18 20]


### Adding and Removing

In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


## Array compatibility

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compatibility Shapes", a.shape == b.shape)

Compatibility Shapes False


In [27]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
with_new_row = np.vstack((original , new_row))
print("With new row: \n", with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original , new_col))
print("With new column: \n", with_new_col)

With new row: 
 [[1 2]
 [3 4]
 [5 6]]
With new column: 
 [[1 2 7]
 [3 4 8]]
