## Numpy array and basics

In [10]:
import numpy as np

### Creating Array From List

In [11]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6],[7,8, 9]])
print("2D Array ", arr_2d)

1D Array  [1 2 3 4 5]
2D Array  [[1 2 3]
 [4 5 6]
 [7 8 9]]


### List vs Numpy array

In [12]:
py_list = [1,2,3]
print("Pyhton list multiplication ", py_list*2)


np_array = np.array([1,2,3]) # element wise multiplication
print("Numpy array multiplication ", np_array*2)


import time

start= time.time()
py_list = [i*2 for i in range(1000000)]
print("\n Python list multiplication time: ", time.time()-start)


start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy array multiplication time: ", time.time()-start)




Pyhton list multiplication  [1, 2, 3, 1, 2, 3]
Numpy array multiplication  [2 4 6]

 Python list multiplication time:  0.08919429779052734

 Numpy array multiplication time:  0.00399017333984375


### Creating array from scratch

In [18]:
zeros = np.zeros((3,4))
print("Zeros Array : \n",zeros)

ones = np.ones((3,4))
print("Ones Array : \n",ones)

full = np.full((3,4),7)
print("Full Array : \n",full)


random = np.random.random((2,3))
print("Random Array : \n",random)


sequence = np.arange(0,10,2)
print("Sequence Array : \n",sequence)


Zeros Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array : 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Random Array : 
 [[0.19597924 0.30627592 0.74741253]
 [0.93878888 0.42625049 0.35222385]]
Sequence Array : 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [23]:
vector = np.array([1,2,3])
print("Vector: \n",vector)

matrix = np.array([[1,2,3],
                  [4,5,6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [25]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("Data Type: ", arr.dtype)


Shape  (2, 3)
Dimension  2
Size  6
Data Type:  int64


### Array Reshaping



In [35]:
arr = np.arange(15)
print("Original Array", arr)

reshaped = arr.reshape((3,5))
print("\n Reshaped Array: ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened Array: ", flattened)


# ravle(returns view instead of copy)
raveled = reshaped.ravel()
print("\n Raveled Array: ", raveled)

transpose = reshaped.T
print("\n Transposed Array: ", transpose)


Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

 Reshaped Array:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

 Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

 Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

 Transposed Array:  [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
