In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],
    [2, 120000, 140000, 160000, 190000],
    [3, 200000, 230000, 260000, 300000],
    [4, 180000, 210000, 240000, 270000],
    [5, 160000, 185000, 205000, 230000]

])


print("\n Sales data shape: ", sales_data.shape)

print("\n Sample Data for !st 3 Restaurant:\n",sales_data[0:3]) # slicing


 Sales data shape:  (5, 5)

 Sample Data for !st 3 Restaurant:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
